"use client";

import { Bot, Check, Copy, GitBranch, Pencil, RefreshCw, Trash2 } from "lucide-react";
import { type FormEvent, useEffect, useRef, useState } from "react";
import type { ChatMessage, ProjectChatMessage } from "../../lib/api/client";
import { Button } from "../ui/button";
import { ConfirmationDialog } from "../ui/confirmation-dialog";
import { Dialog,DialogContent,DialogFooter,DialogHeader } from "../ui/dialog";
import { Label } from "../ui/label";
import { Markdown } from "../ui/markdown";
import { Textarea } from "../ui/textarea";
import { toast } from "../ui/toast";
import { Tooltip, TooltipContent, TooltipProvider } from "../ui/tooltip";

type DisplayChatMessage=ChatMessage&Partial<Pick<ProjectChatMessage,"id"|"version"|"deliveryStatus">>;
interface Props{messages:DisplayChatMessage[];sending:boolean;empty:boolean;loading?:boolean;error?:string;disabled?:boolean;onReload?:(()=>void)|undefined;onEdit?:(message:ProjectChatMessage,content:string)=>Promise<boolean|void>|boolean|void;onDelete?:(message:ProjectChatMessage)=>Promise<void>|void;onBranch?:(message:ProjectChatMessage)=>void;onRetry?:(message:ProjectChatMessage)=>void;}

export function ChatMessageList({messages,sending,empty,loading=false,error="",disabled=false,onReload,onEdit,onDelete,onBranch,onRetry}:Props){
  const [editTarget,setEditTarget]=useState<ProjectChatMessage>();const [draft,setDraft]=useState("");const [editSaving,setEditSaving]=useState(false);const [editError,setEditError]=useState("");const [deleteTarget,setDeleteTarget]=useState<ProjectChatMessage>();
  const messageEnd=useRef<HTMLDivElement>(null);
  const hasStreamingReply=messages.some((message)=>message.id?.startsWith("stream-"));
  const editDirty=Boolean(editTarget&&draft.trim()!==editTarget.content.trim());
  useEffect(()=>{if(editTarget){const current=messages.find((message)=>message.id===editTarget.id) as ProjectChatMessage|undefined;if(!current)setEditTarget(undefined);else if(current.version!==editTarget.version||current.content!==editTarget.content)setEditTarget(current);}if(deleteTarget){const current=messages.find((message)=>message.id===deleteTarget.id) as ProjectChatMessage|undefined;if(!current)setDeleteTarget(undefined);else if(current.version!==deleteTarget.version)setDeleteTarget(current);}},[deleteTarget,editTarget,messages]);
  useEffect(()=>{messageEnd.current?.scrollIntoView({block:"end"});},[messages,sending]);
  async function submitEdit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editTarget||!editDirty||editSaving||disabled)return;setEditSaving(true);setEditError("");try{if(await onEdit?.(editTarget,draft.trim())===false){setEditError("Message could not be updated. Try again.");return;}setEditTarget(undefined);}catch{setEditError("Message could not be updated. Try again.");}finally{setEditSaving(false);}}
  return <TooltipProvider><div className="min-h-0 flex-1 overflow-y-auto p-5 md:p-7" aria-live="polite">{empty?<Empty title="No conversation selected" detail="Choose an endpoint to start a conversation."/>:null}{!empty&&loading&&messages.length===0?<Empty title="Loading conversation" detail="Loading saved messages for this conversation."/>:null}{!empty&&loading&&messages.length>0?<Status>Refreshing conversation...</Status>:null}{!empty&&error?<ConversationError detail={error} retained={messages.length>0} onReload={onReload}/>:null}{!empty&&!loading&&!error&&messages.length===0?<Empty title="Start a conversation" detail="Send a message to the selected project endpoint."/>:null}{messages.map((message,index)=><Message key={message.id??`${message.role}-${index}`} message={message} disabled={disabled||sending} onEdit={message.id&&!message.id.startsWith("stream-")&&message.role==="user"?()=>{setEditTarget(message as ProjectChatMessage);setDraft(message.content);setEditError("");}:undefined} onDelete={message.id&&!message.id.startsWith("stream-")?()=>setDeleteTarget(message as ProjectChatMessage):undefined} onBranch={message.id&&!message.id.startsWith("stream-")?()=>onBranch?.(message as ProjectChatMessage):undefined} onRetry={index===messages.length-1&&message.id&&message.role==="user"&&(message.deliveryStatus==="failed"||message.deliveryStatus==="stopped")?()=>onRetry?.(message as ProjectChatMessage):undefined}/>) }{sending&&!hasStreamingReply?<article className="mb-5 border-l-2 border-border pl-4"><p className="font-mono text-[10px] uppercase tracking-[0.1em] text-tertiary">Assistant</p><p className="mt-1 text-sm text-secondary">Thinking...</p></article>:null}<div ref={messageEnd}/></div>
    <Dialog open={Boolean(editTarget)} onOpenChange={(open)=>{if(!open&&!editSaving){setEditTarget(undefined);setEditError("");}}}><DialogContent><form onSubmit={(event)=>void submitEdit(event)}><DialogHeader title="Edit message" description="Later messages will be removed because they were generated from the previous text."/><div className="px-5 py-5"><Label className="grid gap-2">Message<Textarea aria-label="Message text" value={draft} onChange={(event)=>setDraft(event.target.value)} disabled={editSaving}/></Label>{editError?<p className="mt-3 text-sm text-error" role="alert">{editError}</p>:null}</div><DialogFooter><Button type="button" variant="quiet" onClick={()=>setEditTarget(undefined)} disabled={editSaving}>Cancel</Button><Button type="submit" disabled={!editDirty||disabled||editSaving}>{editSaving?"Saving...":"Save message"}</Button></DialogFooter></form></DialogContent></Dialog>
    <ConfirmationDialog open={Boolean(deleteTarget)} onOpenChange={(open)=>!open&&setDeleteTarget(undefined)} title="Delete message" description="This message and every later message in this conversation will be removed." confirmText="Delete message" confirmDisabled={disabled} onConfirm={()=>deleteTarget?onDelete?.(deleteTarget):undefined} errorContext="Message could not be deleted"/>
  </TooltipProvider>;
}

function Message({message,disabled,onEdit,onDelete,onBranch,onRetry}:{message:DisplayChatMessage;disabled:boolean;onEdit?:(()=>void)|undefined;onDelete?:(()=>void)|undefined;onBranch?:(()=>void)|undefined;onRetry?:(()=>void)|undefined}){const[copied,setCopied]=useState(false);async function copy(){try{await navigator.clipboard.writeText(message.content);setCopied(true);toast.success("Message copied");window.setTimeout(()=>setCopied(false),1500);}catch{toast.error("Message could not be copied");}}
  return <article className={`group mb-5 flex ${message.role==="user"?"justify-end":"justify-start"}`}><div className={`relative max-w-[min(46rem,88%)] ${message.role==="user"?"bg-surface-low p-3":"border-l-2 border-accent pl-4"}`}><div className="mb-1 flex items-center gap-1"><p className="font-mono text-[10px] uppercase tracking-[0.1em] text-tertiary">{message.role==="assistant"?"Assistant":message.role}</p><Action label="Copy message" onClick={()=>void copy()}>{copied?<Check size={15}/>:<Copy size={15}/>}</Action>{onEdit?<Action label="Edit message" disabled={disabled} onClick={onEdit}><Pencil size={15}/></Action>:null}{onBranch&&message.deliveryStatus==="completed"?<Action label="Branch from message" disabled={disabled} onClick={onBranch}><GitBranch size={15}/></Action>:null}{onDelete?<Action label="Delete message" disabled={disabled} onClick={onDelete}><Trash2 size={15}/></Action>:null}</div><Markdown content={message.content}/>{message.deliveryStatus==="failed"||message.deliveryStatus==="stopped"?<div className="mt-2 flex items-center gap-2 text-xs text-error"><span>{message.deliveryStatus==="failed"?"Provider request failed.":"Generation stopped."}</span>{onRetry?<Button size="sm" variant="quiet" disabled={disabled} onClick={onRetry}><RefreshCw size={14}/>Retry</Button>:null}</div>:null}</div></article>;
}
function Action({label,onClick,disabled,children}:{label:string;onClick:()=>void;disabled?:boolean;children:React.ReactNode}){return <Tooltip.Root><Tooltip.Trigger asChild><button type="button" className="grid size-7 place-items-center text-tertiary opacity-100 transition-opacity hover:bg-hover hover:text-foreground focus-visible:opacity-100 disabled:opacity-40 sm:opacity-0 sm:group-hover:opacity-100" aria-label={label} onClick={onClick} disabled={disabled}>{children}</button></Tooltip.Trigger><TooltipContent>{label}</TooltipContent></Tooltip.Root>;}
function Empty({title,detail}:{title:string;detail:string}){return <div className="grid min-h-72 place-items-center text-center"><div><Bot className="mx-auto size-7 text-icon-default"/><h2 className="type-title mt-3 text-foreground">{title}</h2><p className="mt-1 text-sm text-secondary">{detail}</p></div></div>;}
function Status({children}:{children:React.ReactNode}){return <p className="mb-4 border-l-2 border-border pl-3 text-sm text-secondary" role="status">{children}</p>;}
function ConversationError({detail,retained,onReload}:{detail:string;retained:boolean;onReload?:(()=>void)|undefined}){return <div className={retained?"mb-5 border-l-2 border-error pl-3":"grid min-h-72 place-items-center text-center"} role="alert"><div><h2 className="type-title text-error">Conversation unavailable</h2><p className="mt-1 text-sm text-secondary">{detail}</p>{onReload?<Button className="mt-3" size="sm" variant="outline" onClick={onReload}><RefreshCw size={14}/>Retry conversation</Button>:null}</div></div>;}
