"use client";

import { MessageSquare, MessageSquarePlus, Pin, Pencil, Search, Star, Trash2, X } from "lucide-react";
import { type FormEvent, useMemo, useState } from "react";
import type { Endpoint, ProjectChatThread } from "../../lib/api/client";
import { Button } from "../ui/button";
import { ConfirmationDialog } from "../ui/confirmation-dialog";
import { Dialog, DialogContent, DialogFooter, DialogHeader } from "../ui/dialog";
import { Input } from "../ui/input";
import { Label } from "../ui/label";

interface Props { threads:ProjectChatThread[];endpoints:Endpoint[];selectedThreadId:string;disabled:boolean;loading?:boolean;onNewThread:()=>void;onSelect:(id:string)=>void;onRename:(id:string,title:string)=>void;onPin:(id:string,pinned:boolean)=>void;onStar:(id:string,starred:boolean)=>void;onDelete:(id:string)=>void; }

export function ChatThreadRail({threads,endpoints,selectedThreadId,disabled,loading=false,onNewThread,onSelect,onRename,onPin,onStar,onDelete}:Props){
  const [query,setQuery]=useState("");const [renameTarget,setRenameTarget]=useState<ProjectChatThread>();const [renameTitle,setRenameTitle]=useState("");const [deleteTarget,setDeleteTarget]=useState<ProjectChatThread>();
  const visibleThreads=useMemo(()=>{const needle=query.trim().toLocaleLowerCase();return threads.filter((thread)=>!needle||(thread.title??"").toLocaleLowerCase().includes(needle)).sort(compareThreads);},[query,threads]);
  function submitRename(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!renameTarget||!renameTitle.trim())return;onRename(renameTarget.id,renameTitle.trim());setRenameTarget(undefined);}
  return <>
    <aside className="border-b border-border bg-surface-low p-3 lg:border-b-0 lg:border-r"><Button className="w-full" variant="quiet" onClick={onNewThread} disabled={disabled}><MessageSquarePlus size={16}/>New conversation</Button><div className="mt-5"><p className="px-2 font-mono text-[10px] uppercase tracking-[0.1em] text-tertiary">Conversations</p><Label className="relative mt-2 block"><span className="sr-only">Search conversations</span><Search size={15} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-tertiary"/><Input value={query} onChange={(event)=>setQuery(event.target.value)} className="h-9 py-1.5 pl-9 pr-8 text-sm" placeholder="Search conversations"/>{query?<button type="button" className="absolute right-2 top-1/2 grid size-6 -translate-y-1/2 place-items-center text-tertiary hover:text-foreground" aria-label="Clear conversation search" onClick={()=>setQuery("")}><X size={15}/></button>:null}</Label>
      <div className="mt-2 space-y-1">{loading?<p className="px-2 py-3 text-sm text-secondary">Loading conversations...</p>:threads.length===0?<p className="px-2 py-3 text-sm text-secondary">No conversations yet.</p>:visibleThreads.length===0?<div className="px-2 py-4 text-sm text-secondary"><p>No conversations match this search.</p><Button className="mt-2" size="sm" variant="quiet" onClick={()=>setQuery("")}>Clear search</Button></div>:visibleThreads.map((thread)=>{const endpoint=endpoints.find((item)=>item.id===thread.endpointId);return <div key={thread.id} className={`group flex items-center gap-1 px-2 py-1 ${thread.id===selectedThreadId?"bg-surface":"hover:bg-surface"}`}><button type="button" aria-current={thread.id===selectedThreadId?"true":undefined} className="flex min-w-0 flex-1 items-center gap-2 py-1 text-left text-sm" onClick={()=>onSelect(thread.id)}><MessageSquare size={16} className="shrink-0 text-icon-default"/><span className="truncate">{thread.title??endpoint?.name??(thread.endpointId ? "Configured endpoint" : "Deleted endpoint")}</span></button><button type="button" aria-pressed={Boolean(thread.starredAt)} aria-label={thread.starredAt?"Unstar conversation":"Star conversation"} onClick={()=>onStar(thread.id,!thread.starredAt)} disabled={disabled}><Star size={14} className={thread.starredAt?"fill-current text-accent":""}/></button><button type="button" aria-pressed={Boolean(thread.pinnedAt)} aria-label={thread.pinnedAt?"Unpin conversation":"Pin conversation"} onClick={()=>onPin(thread.id,!thread.pinnedAt)} disabled={disabled}><Pin size={14}/></button><button type="button" aria-label="Rename conversation" onClick={()=>{setRenameTarget(thread);setRenameTitle(thread.title??"");}} disabled={disabled}><Pencil size={14}/></button><button type="button" aria-label="Delete conversation" onClick={()=>setDeleteTarget(thread)} disabled={disabled}><Trash2 size={14}/></button></div>;})}</div></div></aside>
    <Dialog open={Boolean(renameTarget)} onOpenChange={(open)=>!open&&setRenameTarget(undefined)}><DialogContent><form onSubmit={submitRename}><DialogHeader title="Rename conversation" description="Choose a title that makes this conversation easy to find."/><div className="px-5 py-5"><Label className="grid gap-2">Conversation title<Input autoFocus required aria-label="Conversation title" value={renameTitle} onChange={(event)=>setRenameTitle(event.target.value)}/></Label></div><DialogFooter><Button type="button" variant="quiet" onClick={()=>setRenameTarget(undefined)}>Cancel</Button><Button type="submit" disabled={!renameTitle.trim()}>Save title</Button></DialogFooter></form></DialogContent></Dialog>
    <ConfirmationDialog open={Boolean(deleteTarget)} onOpenChange={(open)=>!open&&setDeleteTarget(undefined)} title="Delete conversation" description={deleteTarget?`Delete ${deleteTarget.title??"this conversation"}? This removes its saved messages.`:undefined} confirmText="Delete conversation" confirmDisabled={disabled} onConfirm={()=>{if(deleteTarget)onDelete(deleteTarget.id);}} errorContext="Conversation could not be deleted"/>
  </>;
}

function compareThreads(left:ProjectChatThread,right:ProjectChatThread):number{return Number(Boolean(right.starredAt))-Number(Boolean(left.starredAt))||(right.starredAt??"").localeCompare(left.starredAt??"")||Number(Boolean(right.pinnedAt))-Number(Boolean(left.pinnedAt))||(right.pinnedAt??"").localeCompare(left.pinnedAt??"")||right.updatedAt.localeCompare(left.updatedAt);}
