"use client";

import { MessageSquarePlus, Send } from "lucide-react";
import { type FormEvent, useState } from "react";
import type { Endpoint } from "../../lib/api/client";
import { Button } from "../ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../ui/select";
import { Textarea } from "../ui/textarea";

export function ChatComposer({ endpoints, endpointId, hasThread, fixedEndpoint, canStartThread, disabled, onEndpointChange, onStartThread, onSend }: { endpoints: Endpoint[]; endpointId: string; hasThread: boolean; fixedEndpoint: Endpoint | undefined; canStartThread: boolean; disabled: boolean; onEndpointChange: (id: string) => void; onStartThread: () => Promise<boolean>; onSend: (content: string) => Promise<boolean> }) {
  const [draft, setDraft] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const content = draft.trim(); if (!content || disabled) return; if (await onSend(content)) setDraft(""); }
  return <form className="border-t border-border bg-panel p-3 md:p-4" onSubmit={(event) => void submit(event)}><div className="flex flex-col gap-3 sm:flex-row sm:items-end">{hasThread ? <div className="grid gap-1 text-xs text-secondary sm:w-56"><span>Thread endpoint</span><p className="h-9 truncate border border-border bg-surface-low px-2 leading-9 text-sm text-foreground" aria-label="Thread endpoint fixed">{fixedEndpoint ? `${fixedEndpoint.name} (${fixedEndpoint.model})` : "Endpoint unavailable"}</p></div> : <label className="grid gap-1 text-xs text-secondary sm:w-56">Endpoint<Select value={endpointId} disabled={!canStartThread || endpoints.length === 0} onValueChange={onEndpointChange}><SelectTrigger className="h-9" aria-label="Chat endpoint"><SelectValue placeholder="No endpoints" /></SelectTrigger><SelectContent>{endpoints.map((endpoint) => <SelectItem key={endpoint.id} value={endpoint.id}>{endpoint.name} ({endpoint.model})</SelectItem>)}</SelectContent></Select></label>}<label className="sr-only" htmlFor="chat-message">Message</label><Textarea id="chat-message" aria-label="Message" className="min-h-20 flex-1 resize-y" placeholder={hasThread ? "Message the project" : "Start a conversation to send a message"} value={draft} disabled={disabled} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }} />{hasThread ? <Button type="submit" size="icon" aria-label="Send message" title="Send message" disabled={disabled || !draft.trim()}><Send size={17} /></Button> : <Button type="button" onClick={() => void onStartThread()} disabled={!canStartThread || !endpointId} aria-label="Start conversation" title="Start conversation"><MessageSquarePlus size={17} />Start</Button>}</div></form>;
}
