FROM rust:1-bookworm AS build
WORKDIR /src/bash-executor
ARG CARGO_BUILD_JOBS=1
COPY packages/bash-executor ./
RUN cargo build --jobs "$CARGO_BUILD_JOBS" --release --bin bash-executor

WORKDIR /src/botified
COPY third_party/botified ./
RUN cargo build --jobs "$CARGO_BUILD_JOBS" --release --bin botified

FROM debian:bookworm-slim
RUN useradd --system --uid 10001 --gid 0 botified
RUN useradd --system --uid 10002 --gid 0 bash-executor
COPY --from=build /src/botified/target/release/botified /usr/local/bin/botified
COPY --from=build /src/bash-executor/target/release/bash-executor /usr/local/bin/bash-executor
COPY infra/docker/botified-runner-entrypoint.sh /usr/local/bin/botified-runner-entrypoint.sh
USER 10001
ENTRYPOINT ["/usr/local/bin/botified-runner-entrypoint.sh"]
