"use client";

import { KeyRound, Plus, RotateCw, Trash2 } from "lucide-react";
import { type FormEvent, useCallback, useEffect, useState } from "react";
import { ApiError, apiClient, type ProjectCapabilities, type ProjectCredential } from "../../lib/api/client";
import { PageHeader } from "../layout/PageHeader";
import { PageLayout } from "../layout/PageLayout";
import { PageState } from "../layout/PageState";
import { Button } from "../ui/button";
import { ConfirmationDialog } from "../ui/confirmation-dialog";
import { ErrorState } from "../ui/error-state";
import { toast } from "../ui/toast";
import { CredentialDialog } from "./CredentialDialog";

export function CredentialsPage({ projectId }: { projectId: string }) {
  const [items, setItems] = useState<ProjectCredential[]>([]); const [capabilities, setCapabilities] = useState<ProjectCapabilities>(); const [state, setState] = useState<"loading"|"ready"|"error">("loading"); const [error, setError] = useState(""); const [createOpen,setCreateOpen]=useState(false); const [rotate,setRotate]=useState<ProjectCredential>(); const [remove,setRemove]=useState<ProjectCredential>(); const [busy,setBusy]=useState(false);
  const canManage=capabilities?.canManageEndpoints===true;
  const load=useCallback(async()=>{setState("loading");try{const [credentials,projectCapabilities]=await Promise.all([apiClient.credentials(projectId),apiClient.projectCapabilities(projectId)]);setItems(credentials);setCapabilities(projectCapabilities);setError("");setState("ready");}catch(reason){setError(reason instanceof ApiError ? reason.message : "Credentials could not be loaded.");setState("error");}},[projectId]);
  useEffect(()=>{void load();},[load]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);try{const saved=await apiClient.createCredential(projectId,{name:String(form.get("name")||""),baseUrl:String(form.get("baseUrl")||""),secret:String(form.get("secret")||"")});setItems(current=>[...current,saved]);setCreateOpen(false);toast.success("Credential created.");}catch{toast.error("Credential could not be created.");}finally{setBusy(false);}}
  async function rotateCredential(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!rotate)return;setBusy(true);try{const saved=await apiClient.rotateCredential(projectId,rotate.id,String(new FormData(event.currentTarget).get("secret")||""));setItems(current=>current.map(item=>item.id===saved.id?saved:item));setRotate(undefined);toast.success("Credential rotated. Recheck linked endpoints before use.");}catch{toast.error("Credential could not be rotated.");}finally{setBusy(false);}}
  async function deleteCredential(){if(!remove)return;setBusy(true);try{await apiClient.deleteCredential(projectId,remove.id);setItems(current=>current.filter(item=>item.id!==remove.id));setRemove(undefined);toast.success("Credential deleted.");}catch{toast.error("Credential is still in use or could not be deleted.");}finally{setBusy(false);}}
  return <PageLayout header={<PageHeader title="Project credentials" subtitle="Provider keys are write-only and never shown again." actions={canManage?<Button onClick={()=>setCreateOpen(true)}><Plus size={16}/>New credential</Button>:undefined}/>}>{state==="loading"?<PageState state="loading">Loading credentials...</PageState>:null}{state==="error"?<PageState state="error"><ErrorState title="Credentials unavailable" message={error} onRetry={()=>void load()}/></PageState>:null}{state==="ready"?<><p className="mb-5 text-sm text-secondary">{canManage?"Create, rotate, or remove credentials for this project.":"You can view credential metadata, but cannot change credentials."}</p>{items.length===0?<PageState state="empty"><div className="space-y-3"><KeyRound className="text-icon-default"/><p>{canManage?"No credentials yet.":"No credentials are available."}</p>{canManage?<Button onClick={()=>setCreateOpen(true)}>New credential</Button>:null}</div></PageState>:<div className="divide-y divide-subtle border-y border-subtle">{items.map(item=><article key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-medium text-foreground">{item.name}</p><p className="mt-1 text-sm text-secondary">{item.baseUrl} <code className="ml-2">{item.fingerprint}</code></p></div>{canManage?<div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setRotate(item)}><RotateCw size={15}/>Rotate</Button><Button size="icon" variant="danger" aria-label={`Delete ${item.name}`} onClick={()=>setRemove(item)}><Trash2 size={15}/></Button></div>:null}</article>)}</div>}</>:null}<CredentialDialog open={createOpen} onOpenChange={setCreateOpen} title="New credential" busy={busy} onSubmit={create} submit="Create credential" includeName/><CredentialDialog open={Boolean(rotate)} onOpenChange={(open)=>!open&&setRotate(undefined)} title={`Rotate ${rotate?.name??"credential"}`} busy={busy} onSubmit={rotateCredential} submit="Rotate credential"/><ConfirmationDialog open={Boolean(remove)} onOpenChange={(open)=>!open&&setRemove(undefined)} title={`Delete ${remove?.name??"credential"}`} description="This cannot be undone. Endpoints using this credential must be updated first." confirmText="Delete credential" confirmDisabled={busy} onConfirm={deleteCredential} errorContext="Credential could not be deleted"/></PageLayout>;
}
