"use client";

import { KeyRound, Plus } from "lucide-react";
import { type FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { ApiError, apiClient, type ProjectCapabilities, type ProjectCredential } from "../../lib/api/client";
import { useMutationKeys } from "../../lib/api/use-mutation-keys";
import { PageHeader } from "../layout/PageHeader";
import { PageLayout } from "../layout/PageLayout";
import { PageState } from "../layout/PageState";
import { Button } from "../ui/button";
import { ConfirmationDialog } from "../ui/confirmation-dialog";
import { ErrorState } from "../ui/error-state";
import { toast } from "../ui/toast";
import { CredentialDialog } from "./CredentialDialog";
import { CredentialRow } from "./CredentialRow";

export function CredentialsPage({ projectId }: { projectId: string }) {
  const [items, setItems] = useState<ProjectCredential[]>([]); const [capabilities, setCapabilities] = useState<ProjectCapabilities>(); const [state, setState] = useState<"loading"|"ready"|"error">("loading"); const [error, setError] = useState(""); const [capabilitiesError,setCapabilitiesError]=useState(""); const [createOpen,setCreateOpen]=useState(false); const [createProjectId,setCreateProjectId]=useState<string>(); const [rotate,setRotate]=useState<ProjectCredential>(); const [remove,setRemove]=useState<ProjectCredential>(); const [busy,setBusy]=useState(false); const loadRevision=useRef(0); const projectRevision=useRef(0); const currentProjectId=useRef(projectId);
  const mutationKeys=useMutationKeys();
  if(currentProjectId.current!==projectId){currentProjectId.current=projectId;projectRevision.current+=1;mutationKeys.clear("credential.create");}
  const canManage=capabilities?.canManageEndpoints===true;
  const load=useCallback(async()=>{const targetProjectId=projectId;const revision=++loadRevision.current;setState("loading");setCapabilities(undefined);setCapabilitiesError("");try{const [credentialsResult,capabilitiesResult]=await Promise.allSettled([apiClient.credentials(projectId),apiClient.projectCapabilities(projectId)]);if(targetProjectId!==currentProjectId.current||revision!==loadRevision.current)return;if(credentialsResult.status==="rejected")throw credentialsResult.reason;setItems(credentialsResult.value);if(capabilitiesResult.status==="fulfilled")setCapabilities(capabilitiesResult.value);else setCapabilitiesError("Credential permissions could not be loaded. Credentials are read-only until refreshed.");setError("");setState("ready");}catch(reason){if(targetProjectId!==currentProjectId.current||revision!==loadRevision.current)return;setError(reason instanceof ApiError ? reason.message : "Credentials could not be loaded.");setState("error");}},[projectId]);
  useEffect(()=>{setCreateOpen(false);setCreateProjectId(undefined);setRotate(undefined);setRemove(undefined);setBusy(false);void load();},[load]);
  function openCreate(){if(busy)return;mutationKeys.clear("credential.create");setCreateProjectId(projectId);setCreateOpen(true);}
  function mutationError(reason:unknown,fallback:string){if(reason instanceof ApiError&&reason.status===403){setCapabilities(current=>current?{...current,canManageEndpoints:false}:current);setCapabilitiesError("Credential management permission changed. Credentials are now read-only.");setCreateOpen(false);setCreateProjectId(undefined);setRotate(undefined);setRemove(undefined);}return reason instanceof ApiError?reason.message:fallback;}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(createProjectId!==projectId)return;const revision=projectRevision.current;const form=new FormData(event.currentTarget);setBusy(true);try{const saved=await apiClient.createCredential(projectId,{name:String(form.get("name")||""),baseUrl:String(form.get("baseUrl")||""),secret:String(form.get("secret")||"")},mutationKeys.key("credential.create",projectId));mutationKeys.complete("credential.create",projectId);if(revision!==projectRevision.current)return;setItems(current=>[...current,saved]);setCreateOpen(false);setCreateProjectId(undefined);toast.success("Credential created.");}catch(reason){if(reason instanceof ApiError)mutationKeys.complete("credential.create",projectId);if(revision!==projectRevision.current)return;toast.error(mutationError(reason,"Credential could not be created."));}finally{if(revision===projectRevision.current)setBusy(false);}}
  async function rotateCredential(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!rotate||rotate.projectId!==projectId)return;const revision=projectRevision.current;setBusy(true);try{const saved=await apiClient.rotateCredential(projectId,rotate.id,String(new FormData(event.currentTarget).get("secret")||""));if(revision!==projectRevision.current)return;setItems(current=>current.map(item=>item.id===saved.id?saved:item));setRotate(undefined);toast.success("Credential rotated. Recheck linked endpoints before use.");}catch(reason){if(revision!==projectRevision.current)return;toast.error(mutationError(reason,"Credential could not be rotated."));}finally{if(revision===projectRevision.current)setBusy(false);}}
  async function deleteCredential(){if(!remove||remove.projectId!==projectId)return;const revision=projectRevision.current;setBusy(true);try{await apiClient.deleteCredential(projectId,remove.id,remove.version);if(revision!==projectRevision.current)return;setItems(current=>current.filter(item=>item.id!==remove.id));setRemove(undefined);toast.success("Credential deleted.");}catch(reason){if(revision!==projectRevision.current)return;throw new Error(mutationError(reason,"Credential is still in use or could not be deleted."));}finally{if(revision===projectRevision.current)setBusy(false);}}
  return <PageLayout header={<PageHeader title="Project credentials" subtitle="Provider keys are write-only and never shown again." actions={canManage?<Button disabled={busy} onClick={openCreate}><Plus size={16}/>New credential</Button>:undefined}/>}>{capabilitiesError?<div className="mb-4 border border-warning/30 bg-warning/10 px-3 py-2 text-sm text-warning" role="alert">{capabilitiesError}</div>:null}{state==="loading"?<PageState state="loading">Loading credentials...</PageState>:null}{state==="error"?<PageState state="error"><ErrorState title="Credentials unavailable" message={error} onRetry={()=>void load()}/></PageState>:null}{state==="ready"?<><p className="mb-5 text-sm text-secondary">{canManage?"Create, rotate, or remove credentials for this project.":"You can view credential metadata, but cannot change credentials."}</p>{items.length===0?<PageState state="empty"><div className="space-y-3"><KeyRound className="text-icon-default"/><p>{canManage?"No credentials yet.":"No credentials are available."}</p>{canManage?<Button disabled={busy} onClick={openCreate}>New credential</Button>:null}</div></PageState>:<div className="divide-y divide-subtle border-y border-subtle">{items.map(item=><CredentialRow key={item.id} credential={item} canManage={canManage} busy={busy} onRotate={()=>{if(!busy)setRotate(item);}} onDelete={()=>{if(!busy)setRemove(item);}}/>)}</div>}</>:null}<CredentialDialog open={createOpen&&createProjectId===projectId} onOpenChange={(open)=>{setCreateOpen(open);if(!open){mutationKeys.clear("credential.create");setCreateProjectId(undefined);}}} title="New credential" busy={busy} onSubmit={create} submit="Create credential" includeName/><CredentialDialog open={rotate?.projectId===projectId} onOpenChange={(open)=>!open&&setRotate(undefined)} title={`Rotate ${rotate?.name??"credential"}`} busy={busy} onSubmit={rotateCredential} submit="Rotate credential"/><ConfirmationDialog open={remove?.projectId===projectId} onOpenChange={(open)=>!open&&setRemove(undefined)} title={`Delete ${remove?.name??"credential"}`} description="This cannot be undone. Endpoints using this credential must be updated first." confirmText="Delete credential" confirmDisabled={busy} onConfirm={deleteCredential} errorContext="Credential could not be deleted"/></PageLayout>;
}
