"use client";

import { createColumnHelper, getCoreRowModel, useReactTable } from "@tanstack/react-table";
import { MoreHorizontal, Trash2, X } from "lucide-react";
import { useState } from "react";
import type { MemberRole, ProjectMember } from "../../lib/api/client";
import { Badge } from "../ui/badge";
import { Button } from "../ui/button";
import { DataTable } from "../ui/data-table";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../ui/select";
import { memberIdentityLabel, memberRoleLabel } from "./members-page-utils";

const editableRoles: Exclude<MemberRole, "owner">[] = ["admin", "member", "viewer"];
const columns = createColumnHelper<ProjectMember>();
export function MembersTable({ members, canManage, busyUserId, roleError, onDismissRoleError, onChangeRole, onRemove, onView }: { members: ProjectMember[]; canManage: boolean; busyUserId: string | undefined; roleError: { userId: string; message: string } | undefined; onDismissRoleError: () => void; onChangeRole: (member: ProjectMember, role: Exclude<MemberRole, "owner">) => void; onRemove: (member: ProjectMember) => void; onView: (member: ProjectMember) => void }) {
  const [page, setPage] = useState(1); const pageSize = 20; const pageCount = Math.max(1, Math.ceil(members.length / pageSize)); const currentPage = Math.min(page, pageCount); const visible = members.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  const mutationBusy = busyUserId !== undefined;
  const table = useReactTable({ data: visible, columns: [columns.display({ id: "member", header: "Member", cell: ({ row }) => <MemberIdentity member={row.original} /> }), columns.display({ id: "access", header: "Access", cell: ({ row }) => <><MemberRoleControl member={row.original} canManage={canManage} busy={mutationBusy} onChangeRole={onChangeRole} />{roleError?.userId === row.original.userId ? <InlineError message={roleError.message} onDismiss={onDismissRoleError} /> : null}</> }), columns.accessor("createdAt", { header: "Joined", cell: (info) => <span className="text-sm text-secondary">{formatJoined(info.getValue())}</span> }), ...(canManage ? [columns.display({ id: "actions", header: "", cell: ({ row }) => <MemberActions member={row.original} busy={mutationBusy} onRemove={onRemove} /> })] : [])], getCoreRowModel: getCoreRowModel() });
  return <section aria-label="Project members" className="space-y-3"><div className="hidden md:block"><DataTable table={table} testId="members-table" onRowClick={onView} /></div><div className="divide-y divide-subtle rounded-md border border-subtle md:hidden">{visible.map((member) => <article className="space-y-4 p-4" key={member.userId}><button type="button" className="block w-full text-left" onClick={() => onView(member)}><MemberIdentity member={member} /></button><div className="grid grid-cols-2 gap-4"><div><p className="type-caption text-tertiary">Access</p><div className="mt-1"><MemberRoleControl member={member} canManage={canManage} busy={mutationBusy} onChangeRole={onChangeRole} /></div></div><div><p className="type-caption text-tertiary">Joined</p><p className="mt-1 text-sm text-secondary">{formatJoined(member.createdAt)}</p></div></div>{roleError?.userId === member.userId ? <InlineError message={roleError.message} onDismiss={onDismissRoleError} /> : null}{canManage ? <div className="flex justify-end border-t border-subtle pt-3"><MemberActions member={member} busy={mutationBusy} onRemove={onRemove} /></div> : null}</article>)}</div>{pageCount > 1 ? <div className="flex items-center justify-end gap-2"><Button variant="outline" size="sm" disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}>Previous</Button><span className="text-xs text-tertiary">Page {currentPage} of {pageCount}</span><Button variant="outline" size="sm" disabled={currentPage === pageCount} onClick={() => setPage(currentPage + 1)}>Next</Button></div> : null}</section>;
}
function MemberIdentity({ member }: { member: ProjectMember }) { return <div className="grid gap-1"><strong className="break-all font-medium text-foreground">{memberIdentityLabel(member)}</strong>{member.displayName ? <span className="text-xs text-secondary">{member.email}</span> : null}</div>; }
function MemberRoleControl({ member, canManage, busy, onChangeRole }: { member: ProjectMember; canManage: boolean; busy: boolean; onChangeRole: (member: ProjectMember, role: Exclude<MemberRole, "owner">) => void }) { return canManage && member.role !== "owner" ? <Select value={member.role} disabled={busy} onValueChange={(value) => onChangeRole(member, value as Exclude<MemberRole, "owner">)}><SelectTrigger className="h-9 w-32" aria-label={`Role for ${memberIdentityLabel(member)}`} onClick={(event) => event.stopPropagation()}><SelectValue /></SelectTrigger><SelectContent onClick={(event) => event.stopPropagation()}>{editableRoles.map((role) => <SelectItem key={role} value={role}>{memberRoleLabel(role)}</SelectItem>)}</SelectContent></Select> : <Badge variant="outline">{memberRoleLabel(member.role)}</Badge>; }
function MemberActions({ member, busy, onRemove }: { member: ProjectMember; busy: boolean; onRemove: (member: ProjectMember) => void }) { return member.role === "owner" ? <MoreHorizontal size={17} aria-label="Owner actions unavailable" /> : <Button variant="quiet" size="icon" className="text-error" title="Remove member" aria-label={`Remove ${memberIdentityLabel(member)}`} disabled={busy} onClick={(event) => { event.stopPropagation(); onRemove(member); }}><Trash2 size={15} /></Button>; }
function InlineError({ message, onDismiss }: { message: string; onDismiss: () => void }) { return <div className="mt-2 flex items-center justify-between gap-2 text-sm text-error" role="alert"><span>{message}</span><Button variant="quiet" size="icon" aria-label="Dismiss role error" onClick={onDismiss}><X size={15} /></Button></div>; }
function formatJoined(value: string): string { return new Date(value).toLocaleDateString(); }
