"use client";

import { KeyRound, Pencil, RefreshCw, Search, Trash2 } from "lucide-react";
import { Badge, IconButton, Table, TableBody, TableCell, TableHeader, TableHeaderCell, TableRow, TextInput } from "@astryxdesign/core";
import { useMemo, useState } from "react";
import type { Endpoint, EndpointCapability, ProjectCredential } from "../../../lib/api/client";
import { EndpointStatusBadge } from "../EndpointStatusBadge";

export function EndpointsContent({ endpoints, credentials, canManage, canEdit, busy, checkingId, onEdit, onRecheck, onDelete }: { endpoints: Endpoint[]; credentials: ProjectCredential[]; canManage: boolean; canEdit: boolean; busy: boolean; checkingId: string | undefined; onEdit: (endpoint: Endpoint) => void; onRecheck: (endpoint: Endpoint) => void; onDelete: (endpoint: Endpoint) => void }) {
  const [query, setQuery] = useState("");
  const credentialsById = useMemo(() => new Map(credentials.map((credential) => [credential.id, credential])), [credentials]);
  const filtered = useMemo(() => endpoints.filter((endpoint) => `${endpoint.name} ${endpoint.model} ${endpoint.baseUrl}`.toLowerCase().includes(query.trim().toLowerCase())), [endpoints, query]);
  return <section aria-label="Project endpoints" className="space-y-4"><TextInput label="Search endpoints" isLabelHidden startIcon={<Search size={16} />} value={query} onChange={setQuery} className="max-w-sm" placeholder="Search endpoints" size="lg" />{filtered.length === 0 ? <p className="py-6 text-center text-sm text-secondary">No endpoints match this search.</p> : <><div className="hidden md:block"><Table aria-label="Project endpoints" data-testid="endpoints-table" density="balanced" dividers="rows" hasHover verticalAlign="top"><TableHeader><TableRow isHeaderRow><TableHeaderCell>Endpoint</TableHeaderCell><TableHeaderCell>Model</TableHeaderCell><TableHeaderCell>Capabilities</TableHeaderCell><TableHeaderCell>Credential</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell>{canManage ? <TableHeaderCell /> : null}</TableRow></TableHeader><TableBody>{filtered.map((endpoint) => <TableRow key={endpoint.id}><TableCell><EndpointName endpoint={endpoint} /></TableCell><TableCell><span className="font-mono text-xs text-secondary">{endpoint.model}</span></TableCell><TableCell><div className="flex flex-wrap gap-1">{endpoint.capabilities.map((capability: EndpointCapability) => <Badge key={capability} variant="neutral" label={capability.replace("_", " ")} />)}</div></TableCell><TableCell><Credential endpoint={endpoint} credential={credentialsById.get(endpoint.credentialId)} /></TableCell><TableCell><EndpointStatusBadge endpoint={endpoint} /></TableCell>{canManage ? <TableCell><EndpointActions endpoint={endpoint} busy={busy} checking={checkingId === endpoint.id} canEdit={canEdit} onEdit={onEdit} onRecheck={onRecheck} onDelete={onDelete} /></TableCell> : null}</TableRow>)}</TableBody></Table></div><div className="divide-y divide-subtle rounded-md border border-subtle md:hidden">{filtered.map((endpoint) => <EndpointCard endpoint={endpoint} credential={credentialsById.get(endpoint.credentialId)} canManage={canManage} canEdit={canEdit} busy={busy} checking={checkingId === endpoint.id} key={endpoint.id} onEdit={onEdit} onRecheck={onRecheck} onDelete={onDelete} />)}</div></>}</section>;
}
function EndpointCard({ endpoint, credential, canManage, canEdit, busy, checking, onEdit, onRecheck, onDelete }: { endpoint: Endpoint; credential: ProjectCredential | undefined; canManage: boolean; canEdit: boolean; busy: boolean; checking: boolean; onEdit: (endpoint: Endpoint) => void; onRecheck: (endpoint: Endpoint) => void; onDelete: (endpoint: Endpoint) => void }) { return <article className="space-y-4 p-4"><EndpointName endpoint={endpoint} /><dl className="grid grid-cols-2 gap-x-4 gap-y-3 text-sm"><div><dt className="type-caption text-tertiary">Model</dt><dd className="mt-1 break-words font-mono text-secondary">{endpoint.model}</dd></div><div><dt className="type-caption text-tertiary">Status</dt><dd className="mt-1"><EndpointStatusBadge endpoint={endpoint} /></dd></div><div><dt className="type-caption text-tertiary">Capabilities</dt><dd className="mt-1 flex flex-wrap gap-1">{endpoint.capabilities.map((capability) => <Badge key={capability} variant="neutral" label={capability.replace("_", " ")} />)}</dd></div><div><dt className="type-caption text-tertiary">Credential</dt><dd className="mt-1"><Credential endpoint={endpoint} credential={credential} /></dd></div></dl>{canManage ? <div className="flex justify-end gap-2 border-t border-subtle pt-3"><EndpointActions endpoint={endpoint} busy={busy} checking={checking} canEdit={canEdit} onEdit={onEdit} onRecheck={onRecheck} onDelete={onDelete} /></div> : null}</article>; }
function EndpointName({ endpoint }: { endpoint: Endpoint }) { return <div className="grid gap-1"><strong className="font-medium text-foreground">{endpoint.name}</strong><span className="max-w-64 truncate font-mono text-xs text-secondary" title={endpoint.baseUrl}>{endpoint.baseUrl}</span></div>; }
function Credential({ endpoint, credential }: { endpoint: Endpoint; credential: ProjectCredential | undefined }) { return credential ? <span className="inline-flex min-w-0 items-start gap-1.5 text-sm text-secondary"><KeyRound className="mt-0.5 shrink-0" size={14} /><span className="grid min-w-0"><span className="truncate text-foreground">{credential.name}</span><span className="truncate font-mono text-xs text-tertiary" title={credential.fingerprint}>{credential.fingerprint}</span></span></span> : endpoint.hasCredentialRef ? <span className="text-sm text-warning">Credential unavailable</span> : <span className="text-sm text-secondary">Not configured</span>; }
function EndpointActions({ endpoint, busy, checking, canEdit, onEdit, onRecheck, onDelete }: { endpoint: Endpoint; busy: boolean; checking: boolean; canEdit: boolean; onEdit: (endpoint: Endpoint) => void; onRecheck: (endpoint: Endpoint) => void; onDelete: (endpoint: Endpoint) => void }) { return <div className="flex justify-end gap-1"><IconButton variant="ghost" size="md" className="h-9 w-9" label={`Check health for ${endpoint.name}`} isDisabled={busy} onClick={() => onRecheck(endpoint)} icon={<RefreshCw className={checking ? "animate-spin" : ""} size={15} />} /><IconButton variant="ghost" size="md" className="h-9 w-9" label={`Edit ${endpoint.name}`} isDisabled={!canEdit||busy} onClick={() => onEdit(endpoint)} icon={<Pencil size={15} />} /><IconButton variant="ghost" size="md" className="h-9 w-9 text-error" label={`Delete ${endpoint.name}`} isDisabled={busy} onClick={() => onDelete(endpoint)} icon={<Trash2 size={15} />} /></div>; }
