"use client";

import { Plus, Search, Trash2, X } from "lucide-react";
import { Badge, Banner, Button, Dialog, DialogHeader, EmptyState, IconButton, Selector, Spinner, Text, TextInput } from "@astryxdesign/core";
import { type FormEvent, useCallback, useEffect, useId, useRef, useState } from "react";
import { ApiError, apiClient, isReadOnlyMutationError, type WorkspaceDetail, type WorkspaceMember, type WorkspaceMemberRole } from "../../lib/api/client";
import { formatLocalDateTime } from "../../lib/format/date";
import { useMutationKeys } from "../../lib/api/use-mutation-keys";
import { useMemberDirectory } from "../members/useMemberDirectory";
import { PageHeader } from "../layout/PageHeader";
import { PageLayout } from "../layout/PageLayout";

type MutationError={message:string;retry?:()=>void};

export function WorkspaceMembersPage({workspaceId}:{workspaceId:string}){return <WorkspaceMembers key={workspaceId} workspaceId={workspaceId}/>}

function WorkspaceMembers({workspaceId}:{workspaceId:string}){
  const mutationKeys=useMutationKeys(),mounted=useRef(true),workspaceRequest=useRef(0);
  const membersRegionRef=useRef<HTMLElement>(null),removeDescriptionId=useId();
  const fetchMembers=useCallback((query:{q?:string;role?:string;cursor?:string;limit:number})=>apiClient.workspaceMembers(workspaceId,{...(query.q?{q:query.q}:{}),...(query.role?{role:query.role as WorkspaceMemberRole}:{}),...(query.cursor?{cursor:query.cursor}:{}),limit:query.limit}),[workspaceId]);
  const directory=useMemberDirectory<WorkspaceMember>(fetchMembers,workspaceId);
  const [workspace,setWorkspace]=useState<WorkspaceDetail>();
  const [workspaceState,setWorkspaceState]=useState<"loading"|"ready"|"error">("loading");
  const [open,setOpen]=useState(false),[email,setEmail]=useState(""),[role,setRole]=useState<Exclude<WorkspaceMemberRole,"owner">>("member");
  const [busyUserId,setBusyUserId]=useState<string>(),[mutationError,setMutationError]=useState<MutationError>();
  const [selected,setSelected]=useState<WorkspaceMember>(),[memberToRemove,setMemberToRemove]=useState<WorkspaceMember>();

  const loadWorkspace=useCallback(async()=>{const request=++workspaceRequest.current;setWorkspaceState("loading");try{const found=await apiClient.workspace(workspaceId);if(!mounted.current||request!==workspaceRequest.current)return;setWorkspace(found);setWorkspaceState("ready");}catch{if(mounted.current&&request===workspaceRequest.current)setWorkspaceState("error");}},[workspaceId]);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;}},[]);
  useEffect(()=>{void loadWorkspace()},[loadWorkspace]);
  useEffect(()=>{if(!open)mutationKeys.clear("workspace-member.add")},[open]);

  const canManage=workspace?.capabilities.canManageMembers===true,mutationBusy=busyUserId!==undefined;
  async function reload(){await Promise.allSettled([loadWorkspace(),directory.reloadFirst()]);}
  async function recover(reason:unknown,retry:()=>void){
    const stale=reason instanceof ApiError&&(reason.status===404||reason.status===409);
    const access=isReadOnlyMutationError(reason)||reason instanceof ApiError&&reason.status===403;
    if(stale||access){setSelected(undefined);setMemberToRemove(undefined);if(access)setOpen(false);await reload();if(stale)requestAnimationFrame(()=>membersRegionRef.current?.focus({preventScroll:true}));}
    if(reason instanceof ApiError&&reason.status===404&&reason.message==="Workspace not found"){setWorkspace(undefined);setWorkspaceState("error");return;}
    setMutationError({message:errorMessage(reason),...(!stale&&!access?{retry}:{})});
  }
  async function add(event?:FormEvent<HTMLFormElement>){event?.preventDefault();if(!canManage||mutationBusy||!email.trim())return;setBusyUserId("new");setMutationError(undefined);try{await apiClient.addWorkspaceMember(workspaceId,email.trim(),role,mutationKeys.requestKey("workspace-member.add",workspaceId,{email:email.trim(),role}));mutationKeys.complete("workspace-member.add",workspaceId);if(!mounted.current)return;setOpen(false);setEmail("");setRole("member");await reload();}catch(reason){if(reason instanceof ApiError)mutationKeys.complete("workspace-member.add",workspaceId);if(mounted.current)await recover(reason,()=>void add());}finally{if(mounted.current)setBusyUserId(undefined)}}
  async function change(member:WorkspaceMember,next:Exclude<WorkspaceMemberRole,"owner">){if(!canManage||mutationBusy)return;setBusyUserId(member.userId);setMutationError(undefined);const identity=`${member.userId}:${next}`;try{await apiClient.changeWorkspaceMember(workspaceId,member.userId,next,member.updatedAt,mutationKeys.key("workspace-member.change",identity));mutationKeys.complete("workspace-member.change",identity);if(mounted.current){setSelected(undefined);await reload();}}catch(reason){if(reason instanceof ApiError)mutationKeys.complete("workspace-member.change",identity);if(mounted.current)await recover(reason,()=>void change(member,next));}finally{if(mounted.current)setBusyUserId(undefined)}}
  async function remove(member:WorkspaceMember){if(!canManage||mutationBusy)return;setBusyUserId(member.userId);setMutationError(undefined);try{await apiClient.removeWorkspaceMember(workspaceId,member.userId,member.updatedAt,mutationKeys.key("workspace-member.remove",member.userId));mutationKeys.complete("workspace-member.remove",member.userId);if(mounted.current){setMemberToRemove(undefined);await reload();requestAnimationFrame(()=>membersRegionRef.current?.focus({preventScroll:true}));}}catch(reason){if(reason instanceof ApiError)mutationKeys.complete("workspace-member.remove",member.userId);if(mounted.current)await recover(reason,()=>void remove(member));}finally{if(mounted.current)setBusyUserId(undefined)}}

  const initialLoading=workspaceState==="loading"||directory.state==="loading";
  const loadError=workspaceState==="error"||directory.state==="error";
  return <PageLayout header={<PageHeader title="Workspace members" subtitle="People with access to this workspace." actions={canManage?<Button label="Add member" icon={<Plus size={16}/>} variant="primary" size="lg" isDisabled={mutationBusy} onClick={()=>{setMutationError(undefined);setOpen(true)}}/>:undefined}/>}>
    {initialLoading?<div className="flex min-h-48 items-center justify-center"><Spinner label="Loading workspace members..."/></div>:null}
    {loadError?<Banner status="error" title="Workspace members unavailable" description={directory.error||"The workspace members could not be loaded."} endContent={<Button label="Try again" variant="secondary" onClick={()=>void reload()}/>} />:null}
    {workspaceState==="ready"&&directory.state==="ready"?<section ref={membersRegionRef} tabIndex={-1} className="space-y-4 outline-none" aria-label="Workspace members" aria-busy={directory.refreshing}>
      {mutationError&&!open&&!memberToRemove?<MutationNotice error={mutationError} onDismiss={()=>setMutationError(undefined)}/>:null}
      {directory.refreshError?<Banner status="error" title="Members could not be refreshed" description={directory.refreshError} endContent={<Button label="Retry" variant="ghost" onClick={()=>void directory.retry()}/>} />:null}
      <div className="flex flex-wrap items-center gap-3"><TextInput label="Search workspace members" isLabelHidden startIcon={<Search size={16}/>} value={directory.query} onChange={directory.setSearch} className="max-w-sm" placeholder="Search members" size="lg"/><Selector label="Workspace role" isLabelHidden options={[{value:"all",label:"All roles"},{value:"owner",label:"Owner"},{value:"admin",label:"Admin"},{value:"member",label:"Member"},{value:"viewer",label:"Viewer"}]} value={directory.role??"all"} onChange={(value)=>directory.setRole(value==="all"?undefined:value)} size="sm" width={144}/></div>
      {directory.page.items.length===0?<EmptyState title="No workspace members match these filters"/>:<div className="divide-y divide-border border-y border-border">{directory.page.items.map((member)=><WorkspaceMemberRow key={member.userId} member={member} canManage={canManage} busy={mutationBusy} onChange={change} onRemove={(next)=>{setMutationError(undefined);setMemberToRemove(next)}} onView={setSelected}/>)}</div>}
      {directory.page.items.length>0||directory.history.length>0?<div className="flex items-center justify-end gap-2"><Button label="Previous" variant="secondary" size="sm" isDisabled={directory.refreshing||directory.history.length===0} onClick={directory.previous}/><Text type="supporting" color="secondary">Page {directory.history.length+1}</Text><Button label="Next" variant="secondary" size="sm" isDisabled={directory.refreshing||!directory.page.nextCursor} onClick={directory.next}/></div>:null}
      {!canManage?<Text type="supporting" color="secondary">Your workspace access is read-only.</Text>:null}
    </section>:null}
    <Dialog className="[&_button]:min-h-11 [&_button]:min-w-11" isOpen={open} onOpenChange={(next)=>{if(!mutationBusy)setOpen(next)}} purpose="form" padding={0} width="min(34rem, calc(100dvw - 1rem))" maxHeight="calc(100dvh - 1rem)" aria-label="Add workspace member">
      <DialogHeader title="Add workspace member" subtitle="Grant an existing identity access to this workspace." hasDivider {...(!mutationBusy?{onOpenChange:setOpen}:{})}/>
      <div className="min-h-0 min-w-0 flex-1 overflow-y-auto p-4 sm:p-6"><form id="workspace-member-add-form" onSubmit={add}><div className="grid gap-4">{mutationError?<MutationNotice error={mutationError} onDismiss={()=>setMutationError(undefined)}/>:null}<TextInput label="Email" value={email} onChange={setEmail} type="email" hasAutoFocus data-autofocus="" isDisabled={mutationBusy} width="100%"/><Selector label="Workspace member role" options={[{value:"admin",label:"Admin"},{value:"member",label:"Member"},{value:"viewer",label:"Viewer"}]} value={role} onChange={(value)=>setRole(value as Exclude<WorkspaceMemberRole,"owner">)} isDisabled={mutationBusy} size="lg"/></div></form></div>
      <div className="grid min-w-0 shrink-0 grid-cols-1 gap-2 border-t border-border p-4 sm:flex sm:justify-end sm:px-6 [@media(max-height:20rem)]:!grid [@media(max-height:20rem)]:grid-cols-2 [@media(max-height:20rem)]:!p-2 [&>*]:min-w-0 [&>*]:w-full sm:[&>*]:w-auto [@media(max-height:20rem)]:[&>*]:w-full [&_button]:!h-auto [&_button]:min-w-0 [&_button]:whitespace-normal"><Button type="button" label="Cancel" variant="ghost" size="lg" isDisabled={mutationBusy} onClick={()=>setOpen(false)}/><Button label={busyUserId==="new"?"Adding...":"Add member"} type="submit" form="workspace-member-add-form" variant="primary" size="lg" isDisabled={!email.trim()||!canManage||mutationBusy} isLoading={busyUserId==="new"}/></div>
    </Dialog>
    <Dialog className="[&_button]:min-h-11 [&_button]:min-w-11" isOpen={Boolean(selected)} onOpenChange={(next)=>!next&&setSelected(undefined)} purpose="info" padding={0} width="min(34rem, calc(100dvw - 1rem))" maxHeight="calc(100dvh - 1rem)" aria-label="Member details"><DialogHeader title="Member details" subtitle="Workspace membership identity." hasDivider onOpenChange={(next)=>!next&&setSelected(undefined)}/><div className="min-h-0 min-w-0 flex-1 overflow-y-auto p-4 sm:p-6">{selected?<MemberDetails member={selected}/>:null}</div></Dialog>
    <Dialog className="[&_button]:min-h-11 [&_button]:min-w-11" isOpen={Boolean(memberToRemove)} onOpenChange={(next)=>{if(mutationBusy)return;if(!next){setMemberToRemove(undefined);setMutationError(undefined)}}} role="alertdialog" purpose={mutationBusy?"required":"form"} padding={0} width="min(32rem, calc(100dvw - 1rem))" maxHeight="calc(100dvh - 1rem)" aria-label="Remove workspace member" aria-describedby={removeDescriptionId}>
      <DialogHeader title="Remove workspace member" hasDivider/>
      <div className="min-h-0 min-w-0 flex-1 overflow-y-auto p-4 sm:p-6"><Text id={removeDescriptionId} as="p" display="block" color="secondary">{memberToRemove?`Remove ${memberLabel(memberToRemove)} from this workspace? They will lose access to its projects.`:"This member is no longer available."}</Text><div className="mt-4">{mutationError?<MutationNotice error={mutationError} onDismiss={()=>setMutationError(undefined)}/>:null}</div></div>
      <div className="grid min-w-0 shrink-0 grid-cols-1 gap-2 border-t border-border p-4 sm:flex sm:justify-end sm:px-6 [@media(max-height:20rem)]:!grid [@media(max-height:20rem)]:grid-cols-2 [@media(max-height:20rem)]:!p-2 [&>*]:min-w-0 [&>*]:w-full sm:[&>*]:w-auto [@media(max-height:20rem)]:[&>*]:w-full [&_button]:!h-auto [&_button]:min-w-0 [&_button]:whitespace-normal"><Button data-autofocus="" type="button" label="Cancel" variant="ghost" size="lg" isDisabled={mutationBusy} onClick={()=>{setMemberToRemove(undefined);setMutationError(undefined)}}/><Button type="button" label={mutationBusy?"Removing":"Remove member"} variant="destructive" size="lg" isDisabled={!memberToRemove||mutationBusy} isLoading={mutationBusy} onClick={()=>{if(memberToRemove&&!mutationBusy)void remove(memberToRemove)}}/></div>
    </Dialog>
  </PageLayout>
}

function WorkspaceMemberRow({member,canManage,busy,onChange,onRemove,onView}:{member:WorkspaceMember;canManage:boolean;busy:boolean;onChange:(member:WorkspaceMember,role:Exclude<WorkspaceMemberRole,"owner">)=>void;onRemove:(member:WorkspaceMember)=>void;onView:(member:WorkspaceMember)=>void}){const label=memberLabel(member);return <div className="flex flex-wrap items-center justify-between gap-3 py-3"><button type="button" className="min-w-0 text-left" onClick={()=>onView(member)}><div className="flex flex-wrap items-center gap-2"><Text maxLines={1}>{label}</Text>{member.role==="owner"?<Badge variant="neutral" label="Owner"/>:null}</div>{member.displayName?<Text type="supporting" color="secondary" display="block" maxLines={1}>{member.email}</Text>:null}</button>{canManage&&member.role!=="owner"?<div className="flex gap-2"><Selector label={`Role for ${label}`} isLabelHidden options={[{value:"admin",label:"Admin"},{value:"member",label:"Member"},{value:"viewer",label:"Viewer"}]} value={member.role} onChange={(value)=>onChange(member,value as Exclude<WorkspaceMemberRole,"owner">)} isDisabled={busy} size="lg" className="w-28"/><IconButton label={`Remove ${label}`} icon={<Trash2 size={15}/>} variant="destructive" size="lg" isDisabled={busy} onClick={()=>onRemove(member)}/></div>:null}</div>}
function MemberDetails({member}:{member:WorkspaceMember}){return <dl className="grid gap-4 sm:grid-cols-[8rem_1fr]"><dt><Text color="secondary">Name</Text></dt><dd><Text wordBreak="break-all">{memberLabel(member)}</Text></dd><dt><Text color="secondary">Email</Text></dt><dd><Text wordBreak="break-all">{member.email}</Text></dd><dt><Text color="secondary">Role</Text></dt><dd><Text>{member.role}</Text></dd><dt><Text color="secondary">Joined</Text></dt><dd><Text>{formatLocalDateTime(member.createdAt)}</Text></dd></dl>}
function MutationNotice({error,onDismiss}:{error:MutationError;onDismiss:()=>void}){return <Banner status="error" title="Member update failed" description={error.message} endContent={<span className="flex gap-2">{error.retry?<Button label="Retry" size="md" variant="ghost" onClick={error.retry}/>:null}<IconButton label="Dismiss member error" icon={<X size={15}/>} size="lg" variant="ghost" onClick={onDismiss}/></span>}/>}
function memberLabel(member:WorkspaceMember):string{return member.displayName||member.email||"Workspace member"}
function errorMessage(reason:unknown):string{return reason instanceof ApiError?reason.message:"The member request could not be completed."}
