"use client";

import type { ProjectUsageOverview, ProjectUsageWindow } from "../../lib/api/client";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../ui/select";

const labels = { activeTasks: "Active tasks", providerRequests: "Provider requests", providerTokens: "Provider tokens", providerCost: "Provider cost", projectFileBytes: "Project file storage" } as const;

export function UsageView({ overview, selectedEndpointId, onEndpointChange }: { overview: ProjectUsageOverview; selectedEndpointId: string; onEndpointChange: (endpointId: string) => void }) {
  const peak = Math.max(1, ...overview.daily.map((day) => day.requests));
  const hasTrend = overview.daily.some((day) => day.requests > 0 || day.tokens > 0 || day.cost > 0);
  const selectedEndpoint = overview.endpoints.find((endpoint) => endpoint.endpointId === selectedEndpointId);
  const scopeLabel = selectedEndpointId === "all" ? "All endpoints" : (selectedEndpoint?.endpointName ?? selectedEndpointId);
  return <section className="space-y-7" aria-label="Project usage">
    <section className="flex flex-wrap items-end justify-between gap-3 border-y border-border py-4" aria-labelledby="usage-scope"><div><h2 id="usage-scope" className="type-title text-foreground">Usage scope</h2><p className="mt-1 max-w-2xl text-sm text-secondary">The endpoint filter applies to your settled 30-day provider usage. Project lifetime limits and settled endpoint totals remain project-wide; rolling endpoint limits show your capacity.</p></div><label className="grid gap-1 text-xs text-secondary">Endpoint<Select value={selectedEndpointId} onValueChange={onEndpointChange}><SelectTrigger aria-label="Usage scope endpoint" className="h-9 w-56"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All endpoints</SelectItem>{overview.endpoints.filter((endpoint) => endpoint.endpointId !== null).map((endpoint) => <SelectItem key={endpoint.endpointId} value={endpoint.endpointId!}>{endpoint.endpointName}</SelectItem>)}</SelectContent></Select></label></section>
    <section aria-labelledby="usage-limits"><div><h2 id="usage-limits" className="type-title text-foreground">Project limits</h2><p className="mt-1 text-sm text-secondary">Project-wide, independent of the endpoint filter.</p><p className="mt-1 text-xs text-tertiary">Provider totals include conservative reservations when final delivery usage is unknown.</p></div><dl className="mt-4 grid overflow-hidden border border-border sm:grid-cols-2 xl:grid-cols-5">{overview.limits.map((limit, index) => <div key={limit.metric} className={`min-w-0 border-b border-border p-4 sm:border-r sm:last:border-r-0 xl:border-b-0 ${index >= 2 ? "sm:border-b-0" : ""}`}><dt className="type-caption text-tertiary">{labels[limit.metric]}</dt><dd className="mt-3 text-xl text-foreground">{formatMetric(limit.metric, limit.current)}</dd><p className="mt-1 text-xs text-secondary">{limit.limit === null ? "No limit" : `${formatMetric(limit.metric, limit.remaining!)} remaining of ${formatMetric(limit.metric, limit.limit)}`}</p><p className="mt-2 text-xs text-tertiary">{formatUsageWindow(limit.window)}</p></div>)}</dl></section>
    <section className="border-y border-border py-5" aria-labelledby="usage-trend"><div><h2 id="usage-trend" className="type-title text-foreground">Your 30-day trend</h2><p className="mt-1 text-sm text-secondary">Your settled provider requests · {scopeLabel}.</p></div>{hasTrend ? <><div className="mt-5 flex h-40 items-end gap-px border-b border-border" aria-label="30-day request trend">{overview.daily.map((day) => <div className="group relative min-w-0 flex-1 bg-accent/75 hover:bg-accent" key={day.date} style={{ height: `${day.requests === 0 ? 0 : Math.max(3, Math.round(day.requests / peak * 100))}%` }} title={`${day.date}: ${day.requests} requests, ${day.tokens} tokens, ${formatCost(day.cost)}`} aria-label={`${day.date}: ${day.requests} requests`} />)}</div><div className="mt-2 flex justify-between text-xs text-tertiary"><span>{overview.daily[0]?.date}</span><span>{overview.daily.at(-1)?.date}</span></div><dl className="mt-5 grid gap-3 sm:grid-cols-3"><UsageTotal label="Requests" value={String(overview.trendTotals.requests)} /><UsageTotal label="Tokens" value={formatNumber(overview.trendTotals.tokens)} /><UsageTotal label="Cost" value={formatCost(overview.trendTotals.cost)} /></dl></> : <div className="grid min-h-40 place-items-center border border-dashed border-border px-5 text-center"><p className="text-sm text-secondary">No settled provider usage in this period.</p></div>}</section>
    <section aria-labelledby="usage-endpoints"><h2 id="usage-endpoints" className="type-title text-foreground">Project endpoint usage</h2><p className="mt-1 text-sm text-secondary">Settled totals from the last 30 days, including activity not tied to a current endpoint.</p>{overview.endpoints.length === 0 ? <p className="mt-3 text-sm text-secondary">No project endpoint usage in this period.</p> : <div className="mt-4 divide-y divide-border border border-border">{overview.endpoints.map((endpoint) => <div className="flex flex-wrap items-start justify-between gap-3 px-4 py-3" key={endpoint.endpointId ?? "unassigned-endpoints"}><p className="text-sm text-foreground">{endpoint.endpointName}</p><div className="text-right"><p className="text-xs text-secondary">{endpoint.requests} requests · {formatNumber(endpoint.tokens)} tokens · {formatCost(endpoint.cost)}</p>{endpoint.limits?.map(limit=><p className="mt-1 text-xs text-tertiary" key={limit.metric}>Your {labels[limit.metric].toLowerCase()}: {limit.remaining===null?"unlimited":`${formatMetric(limit.metric,limit.remaining)} remaining`} · {formatUsageWindow(limit.window)}</p>)}</div></div>)}</div>}</section>
  </section>;
}

function UsageTotal({ label, value }: { label: string; value: string }) { return <div><dt className="type-caption text-tertiary">{label}</dt><dd className="mt-1 text-lg text-foreground">{value}</dd></div>; }
function formatMetric(metric: keyof typeof labels, value: number): string { return metric === "providerCost" ? formatCost(value) : metric === "projectFileBytes" ? formatBytes(value) : formatNumber(value); }
function formatNumber(value: number): string { return new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(value); }
function formatCost(value: number): string { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2, maximumFractionDigits: 6 }).format(value); }
function formatBytes(value: number): string { if (value < 1024) return `${value} B`; if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KiB`; return `${(value / (1024 * 1024)).toFixed(1)} MiB`; }
function formatDate(value: string): string { return new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(new Date(value)); }
function formatUsageWindow(window: ProjectUsageWindow): string { return window.kind === "current_gauge" ? "Current state" : window.kind === "rolling" ? window.resetAt ? `${duration(window.windowSeconds)} rolling · resets ${new Intl.DateTimeFormat("en-US",{timeStyle:"short"}).format(new Date(window.resetAt))}` : `${duration(window.windowSeconds)} rolling · no usage in window` : `Project lifetime · started ${formatDate(window.startedAt)}`; }
function duration(seconds:number){if(seconds%86400===0)return `${seconds/86400}d`;if(seconds%3600===0)return `${seconds/3600}h`;return `${seconds}s`;}
