import type { AlertRuleMetric, AlertRuleScope, ProjectAlertRule, ProjectAlertType } from "../../contracts/src/api.js";
import { newId, nowIso } from "../../domain/src/ids.js";
import { ProductError, NotFoundError } from "../../domain/src/errors.js";
import type { ProductStore } from "../../ports/src/store.js";
import { AuthorizationService } from "./authorizationService.js";

const types = new Set<ProjectAlertType>(["active_tasks_limit","provider_requests_limit","provider_tokens_limit","provider_cost_limit","project_file_bytes_limit","endpoint_failure","provider_failure","task_failure","sandbox_failure"]);
const metrics = new Set<AlertRuleMetric>(["active_tasks","provider_requests","provider_tokens","provider_cost","project_file_bytes","failure_count"]);
type Input={name?:unknown;alertType?:unknown;metric?:unknown;threshold?:unknown;windowSeconds?:unknown;scope?:unknown;enabled?:unknown};
type RuleAuditAction="alert.rule.create"|"alert.rule.update"|"alert.rule.delete";

export class AlertRuleService {
  constructor(private readonly store: ProductStore, private readonly authorization: AuthorizationService) {}
  async list(userId:string,projectId:string){await this.authorization.requireProject(userId,projectId);return this.store.listProjectAlertRules(projectId)}
  async create(userId:string,projectId:string,input:Input){await this.authorization.requireProject(userId,projectId,"admin");const timestamp=nowIso();const type=alertType(input.alertType);const selectedMetric=metric(input.metric,type);const value:ProjectAlertRule={id:newId("alert_rule"),projectId,name:text(input.name,"name",type.replaceAll("_"," ")),alertType:type,metric:selectedMetric,condition:"greater_than_or_equal",threshold:number(input.threshold,"threshold",1),windowSeconds:window(input.windowSeconds,selectedMetric),scope:await this.scope(projectId,input.scope),enabled:input.enabled===undefined?true:boolean(input.enabled,"enabled"),createdAt:timestamp,updatedAt:timestamp};const saved=await this.store.createProjectAlertRule(value);await this.audit(projectId,userId,"alert.rule.create",saved.id);return saved}
  async update(userId:string,projectId:string,id:string,input:Input){await this.authorization.requireProject(userId,projectId,"admin");const current=(await this.store.listProjectAlertRules(projectId)).find(rule=>rule.id===id);if(!current)throw new NotFoundError("Alert rule not found");const type=input.alertType===undefined?current.alertType:alertType(input.alertType);const selectedMetric=input.metric===undefined?(current.metric??defaultMetric(type)):metric(input.metric,type);if(!metricFor(type,selectedMetric))throw new ProductError("metric is invalid for alertType");const updated:ProjectAlertRule={...current,name:input.name===undefined?(current.name??type.replaceAll("_"," ")):text(input.name,"name"),alertType:type,metric:selectedMetric,condition:"greater_than_or_equal",threshold:input.threshold===undefined?(current.threshold??1):number(input.threshold,"threshold"),windowSeconds:input.windowSeconds===undefined?(current.windowSeconds??defaultWindow(selectedMetric)):window(input.windowSeconds,selectedMetric),scope:input.scope===undefined?(current.scope??{kind:"project"}):await this.scope(projectId,input.scope),enabled:input.enabled===undefined?current.enabled:boolean(input.enabled,"enabled"),updatedAt:nowIso()};const saved=await this.store.updateProjectAlertRule(updated);if(!saved)throw new NotFoundError("Alert rule not found");await this.audit(projectId,userId,"alert.rule.update",id);return saved}
  async remove(userId:string,projectId:string,id:string){await this.authorization.requireProject(userId,projectId,"admin");if(!await this.store.deleteProjectAlertRule(projectId,id))throw new NotFoundError("Alert rule not found");await this.audit(projectId,userId,"alert.rule.delete",id);return{deleted:true as const}}
  async test(userId:string,projectId:string,id:string){await this.authorization.requireProject(userId,projectId,"admin");const rule=(await this.store.listProjectAlertRules(projectId)).find(item=>item.id===id);if(!rule)throw new NotFoundError("Alert rule not found");const evaluatedAt=nowIso();const value=await measureAlertRule(this.store,rule,evaluatedAt);const threshold=rule.threshold??1;return{matched:matchesAlertRule(rule,value),metric:rule.metric??defaultMetric(rule.alertType),value,threshold,evaluatedAt}}
  async acknowledge(userId:string,projectId:string,id:string){await this.authorization.requireProject(userId,projectId,"admin");const now=nowIso();const alert=await this.store.updateProjectAlertState(projectId,id,{acknowledgedAt:now,acknowledgedBy:userId},now);if(!alert)throw new NotFoundError("Active project alert not found");await this.instanceAudit(projectId,userId,"alert.acknowledge",id);return alert}
  async silence(userId:string,projectId:string,id:string,until:unknown){await this.authorization.requireProject(userId,projectId,"admin");const value=until===null?null:timestamp(until);if(value!==null&&(Date.parse(value)<=Date.now()||Date.parse(value)>Date.now()+30*86400000))throw new ProductError("silencedUntil must be in the next 30 days");const alert=await this.store.updateProjectAlertState(projectId,id,{silencedUntil:value},nowIso());if(!alert)throw new NotFoundError("Active project alert not found");await this.instanceAudit(projectId,userId,"alert.silence",id);return alert}
  private async scope(projectId:string,value:unknown):Promise<AlertRuleScope>{if(value===undefined)return{kind:"project"};if(!value||typeof value!=="object")throw new ProductError("scope is invalid");const input=value as Record<string,unknown>;if(input.kind==="project")return{kind:"project"};if(input.kind!=="endpoint"||typeof input.endpointId!=="string")throw new ProductError("scope is invalid");const endpoint=await this.store.findEndpoint(input.endpointId);if(!endpoint||endpoint.projectId!==projectId)throw new ProductError("Alert rule endpoint not found",404);return{kind:"endpoint",endpointId:input.endpointId}}
  private async audit(projectId:string,userId:string,action:RuleAuditAction,id:string){await this.store.appendProjectAuditEvent({id:newId("audit"),projectId,actorId:userId,action,status:"accepted",resourceKind:"alert",resourceId:id,detail:{alertRuleId:id},createdAt:nowIso()})}
  private async instanceAudit(projectId:string,userId:string,action:"alert.acknowledge"|"alert.silence",id:string){await this.store.appendProjectAuditEvent({id:newId("audit"),projectId,actorId:userId,action,status:"accepted",resourceKind:"alert",resourceId:id,detail:{alertId:id},createdAt:nowIso()})}
}
export async function measureAlertRule(store:ProductStore,rule:ProjectAlertRule,now=nowIso()):Promise<number>{return store.measureProjectAlertRule({projectId:rule.projectId,alertType:rule.alertType,metric:rule.metric??defaultMetric(rule.alertType),windowSeconds:rule.windowSeconds??null,endpointId:rule.scope?.kind==="endpoint"?rule.scope.endpointId:null,now})}
export function matchesAlertRule(rule:ProjectAlertRule,value:number):boolean{return value>=(rule.threshold??1)}
function alertType(value:unknown){if(typeof value!=="string"||!types.has(value as ProjectAlertType))throw new ProductError("alertType is invalid");return value as ProjectAlertType}
function defaultMetric(type:ProjectAlertType):AlertRuleMetric{return type==="active_tasks_limit"?"active_tasks":type==="provider_requests_limit"?"provider_requests":type==="provider_tokens_limit"?"provider_tokens":type==="provider_cost_limit"?"provider_cost":type==="project_file_bytes_limit"?"project_file_bytes":"failure_count"}
function metric(value:unknown,type:ProjectAlertType){const selected=value===undefined?defaultMetric(type):typeof value==="string"&&metrics.has(value as AlertRuleMetric)?value as AlertRuleMetric:null;if(selected===null||!metricFor(type,selected))throw new ProductError("metric is invalid for alertType");return selected}
function metricFor(type:ProjectAlertType,selected:AlertRuleMetric):boolean{return selected===defaultMetric(type)}
function text(value:unknown,field:string,fallback?:string){if(value===undefined&&fallback)return fallback;if(typeof value!=="string"||value.trim().length<1||value.trim().length>80)throw new ProductError(`${field} must be 1 to 80 characters`);return value.trim()}
function number(value:unknown,field:string,fallback?:number){if(value===undefined&&fallback!==undefined)return fallback;if(typeof value!=="number"||!Number.isFinite(value)||value<0)throw new ProductError(`${field} must be a non-negative number`);return value}
function window(value:unknown,selectedMetric:AlertRuleMetric){if(value===undefined)return defaultWindow(selectedMetric);if(value===null){if(selectedMetric==="failure_count")throw new ProductError("windowSeconds is required for failure_count");return null}if(typeof value!=="number"||!Number.isInteger(value)||value<60||value>2592000)throw new ProductError("windowSeconds must be between 60 and 2592000");return value}
function defaultWindow(selectedMetric:AlertRuleMetric):number|null{return selectedMetric==="failure_count"?3600:null}
function boolean(value:unknown,field:string){if(typeof value!=="boolean")throw new ProductError(`${field} must be a boolean`);return value}
function timestamp(value:unknown){if(typeof value!=="string"||!Number.isFinite(Date.parse(value)))throw new ProductError("silencedUntil must be an ISO timestamp");return new Date(value).toISOString()}
