import { createHash } from "node:crypto";
import type { CreateProjectCredentialInput, CredentialDirectoryQuery, CredentialPage, ProjectCredential, RotateProjectCredentialInput, StoredProjectCredential } from "../../contracts/src/api.js";
import { NotFoundError, ProductError } from "../../domain/src/errors.js";
import { newId, nowIso } from "../../domain/src/ids.js";
import { PRODUCT_NAME_MAX_LENGTH, requireNonEmptyString } from "../../domain/src/validation.js";
import { normalizeOpenAICompatibleBaseUrl } from "../../openai-compatible-client/src/index.js";
import type { ProductStore } from "../../ports/src/store.js";
import { credentialAad, type CredentialCrypto } from "./credentialCrypto.js";
import { AuthorizationService } from "./authorizationService.js";
import { runIdempotentMutation } from "./idempotentMutation.js";
import { decodeProviderDirectoryCursor, encodeProviderDirectoryCursor, normalizeProviderDirectoryQuery, providerDirectoryLimit, type ProviderDirectoryScope } from "./endpointCredentialDirectory.js";

export class CredentialService {
  constructor(private readonly store: ProductStore, private readonly authorization: AuthorizationService, private readonly crypto: CredentialCrypto) {}
  async list(userId:string,projectId:string,query:CredentialDirectoryQuery={}):Promise<CredentialPage>{await this.authorization.requireProject(userId,projectId,"view");const q=normalizeProviderDirectoryQuery(query.q),limit=providerDirectoryLimit(query.limit),scope:ProviderDirectoryScope={actorId:userId,projectId,kind:"credentials",q,mode:null};const after=query.cursor!==undefined?decodeProviderDirectoryCursor(query.cursor,scope):undefined;const rows=await this.store.listProjectCredentialDirectoryPage(projectId,{q,...(after?{after}:{}),limit:limit+1}),items=rows.slice(0,limit),last=items.at(-1);return{items,nextCursor:rows.length>limit&&last?encodeProviderDirectoryCursor(scope,{createdAt:last.createdAt,id:last.id}):null}}
  async get(userId:string,projectId:string,id:string):Promise<ProjectCredential>{await this.authorization.requireProject(userId,projectId,"view");const value=await this.store.findProjectCredentialView(projectId,id);if(!value)throw new NotFoundError("Credential not found");return value}
  async create(userId:string, projectId:string, input:CreateProjectCredentialInput, idempotencyKey?:string): Promise<ProjectCredential> { await this.authorization.requireProject(userId,projectId,"admin"); const name=requireNonEmptyString(input.name,"credential.name",PRODUCT_NAME_MAX_LENGTH);const baseUrl=normalizeOpenAICompatibleBaseUrl(required(input.baseUrl,"credential.baseUrl"));const secret=required(input.secret,"credential.secret");const create=async(id:string)=>{const existing=await this.store.findProjectCredentialView(projectId,id);if(existing)return existing;const now=nowIso();const saved=await this.store.createProjectCredential(this.encrypt({id,projectId,name,baseUrl,secret,version:1,createdAt:now,lastRotatedAt:null,updatedAt:now}));await this.audit(projectId,userId,"credential.create",saved.id,{credentialVersion:saved.version});return saved;};if(!idempotencyKey)return create(newId("cred"));return runIdempotentMutation({store:this.store,actorId:userId,scopeId:projectId,operation:"project.credential.create",key:idempotencyKey,request:{projectId,name,baseUrl,secret},resourceId:newId("cred"),failureMessage:"Credential could not be created",run:create}); }
  async rotate(userId:string, projectId:string, credentialId:string, input:RotateProjectCredentialInput,idempotencyKey?:string): Promise<ProjectCredential> { await this.authorization.requireProject(userId,projectId,"admin");const secret=required(input.secret,"credential.secret");const rotate=async()=>{const existing=await this.require(projectId,credentialId); const now=nowIso(); const updated=this.encrypt({id:existing.id,projectId,name:existing.name,baseUrl:existing.baseUrl,secret,version:existing.version+1,createdAt:existing.createdAt,lastRotatedAt:now,updatedAt:now}); const saved=await this.store.updateProjectCredential(updated,existing.version); if(saved==="not_found") throw new NotFoundError("Credential not found"); if(saved==="version_conflict") throw new ProductError("Credential was rotated by another request",409); await this.audit(projectId,userId,"credential.rotate",saved.id,{credentialVersion:saved.version}); return saved;};if(!idempotencyKey)return rotate();return runIdempotentMutation({store:this.store,actorId:userId,scopeId:projectId,operation:"project.credential.rotate",key:idempotencyKey,request:{projectId,credentialId,secret},resourceId:credentialId,failureMessage:"Credential could not be rotated",run:rotate}); }
  async remove(userId:string, projectId:string, credentialId:string, expectedVersion:number, idempotencyKey?:string): Promise<void> { await this.authorization.requireProject(userId,projectId,"admin"); if(!Number.isInteger(expectedVersion)||expectedVersion<1)throw new ProductError("expectedVersion is required to delete credential");const remove=async()=>{const result=await this.store.deleteProjectCredential(credentialId,projectId,expectedVersion);if(result==="not_found")throw new NotFoundError("Credential not found");if(result==="version_conflict")throw new ProductError("Credential changed elsewhere. Refresh and try again.",409);if(result==="referenced_by_endpoints")throw new ProductError("Credential cannot be deleted while endpoints reference it",409);await this.audit(projectId,userId,"credential.delete",credentialId,{credentialVersion:expectedVersion});return{deleted:true as const}};if(!idempotencyKey){await remove();return}await runIdempotentMutation({store:this.store,actorId:userId,scopeId:projectId,operation:"project.credential.delete",key:idempotencyKey,request:{projectId,credentialId,expectedVersion},resourceId:credentialId,failureMessage:"Credential could not be deleted",run:remove}); }
  async resolve(projectId:string, credentialId:string): Promise<{apiKey:string;baseUrl:string;version:number}> { const value=await this.require(projectId,credentialId); return {apiKey:this.crypto.decrypt({algorithm:"aes-256-gcm",keyId:value.keyId,nonce:Buffer.from(value.nonce),ciphertext:Buffer.from(value.ciphertext),authTag:Buffer.from(value.authTag)},credentialAad({credentialId:value.id,projectId:value.projectId,type:"api_key",version:value.version})),baseUrl:value.baseUrl,version:value.version}; }
  private async require(projectId:string,id:string): Promise<StoredProjectCredential> { const value=await this.store.findStoredProjectCredential(projectId,id); if(!value) throw new NotFoundError("Credential not found"); return value; }
  private async audit(projectId:string,actorId:string,action:Extract<import("../../contracts/src/api.js").ProjectAuditAction,`credential.${string}`>,resourceId:string,detail:import("../../contracts/src/api.js").ProjectAuditSafeDetail):Promise<void>{await this.store.appendProjectAuditEvent({id:newId("audit"),projectId,actorId,action,status:"accepted",resourceKind:"credential",resourceId,detail,createdAt:nowIso()})}
  private encrypt(input:{id:string;projectId:string;name:string;baseUrl:string;secret:string;version:number;createdAt:string;lastRotatedAt:string|null;updatedAt:string}): StoredProjectCredential { const encrypted=this.crypto.encrypt(input.secret,credentialAad({credentialId:input.id,projectId:input.projectId,type:"api_key",version:input.version})); return {id:input.id,projectId:input.projectId,name:input.name,type:"api_key",baseUrl:input.baseUrl,fingerprint:createHash("sha256").update(input.secret).digest("hex").slice(0,16),version:input.version,createdAt:input.createdAt,lastRotatedAt:input.lastRotatedAt,updatedAt:input.updatedAt,keyId:encrypted.keyId,nonce:encrypted.nonce,ciphertext:encrypted.ciphertext,authTag:encrypted.authTag}; }
}
function required(value:string,name:string): string { const normalized=value.trim(); if(!normalized) throw new ProductError(`${name} is required`); return normalized; }
