import type { ManagedWorkspaceMembershipRole, StoredUser, WorkspaceMembershipView } from "../../contracts/src/api.js";
import { NotFoundError, ProductError } from "../../domain/src/errors.js";
import { newId, nowIso } from "../../domain/src/ids.js";
import type { ProductStore } from "../../ports/src/store.js";
import { AuthorizationService } from "./authorizationService.js";
import { runIdempotentMutation } from "./idempotentMutation.js";

type Identity = { email?: string; issuer?: string; subject?: string };

export class WorkspaceMembershipService {
  constructor(private readonly store: ProductStore, private readonly authorization: AuthorizationService) {}
  async list(actor:string,workspaceId:string){await this.authorization.requireWorkspace(actor,workspaceId);return this.store.listWorkspaceMemberships(workspaceId)}
  async add(actor:string,workspaceId:string,identity:Identity,role:ManagedWorkspaceMembershipRole,idempotencyKey?:string){await this.authorization.requireWorkspace(actor,workspaceId,"admin");const user=await this.find(identity);const create=async()=>{const timestamp=nowIso();const created=await this.store.createWorkspaceMembership({workspaceId,userId:user.id,role,createdAt:timestamp,updatedAt:timestamp});if(created==="already_exists")throw new ProductError("Workspace membership already exists",409);return this.view(workspaceId,user.id)};if(!idempotencyKey)return create();return runIdempotentMutation({store:this.store,actorId:actor,scopeId:workspaceId,operation:"workspace.member.add",key:idempotencyKey,request:{workspaceId,userId:user.id,role},resourceId:user.id,failureMessage:"Workspace member could not be added",run:create})}
  async change(actor:string,workspaceId:string,userId:string,role:ManagedWorkspaceMembershipRole,expectedUpdatedAt:string,idempotencyKey?:string){await this.authorization.requireWorkspace(actor,workspaceId,"admin");const expected=expectedTimestamp(expectedUpdatedAt);const change=async()=>{const result=await this.store.updateManagedWorkspaceMembershipRole(workspaceId,userId,role,nextTimestamp(expected),expected);if(result==="not_found")throw new NotFoundError("Workspace membership not found");if(result==="owner")throw new ProductError("Workspace owner membership cannot be changed or removed",409);if(result==="conflict")throw membershipChangedElsewhere();return this.view(workspaceId,userId)};if(!idempotencyKey)return change();return runIdempotentMutation({store:this.store,actorId:actor,scopeId:workspaceId,operation:"workspace.member.change",key:idempotencyKey,request:{workspaceId,userId,role,expectedUpdatedAt:expected},resourceId:userId,failureMessage:"Workspace member role could not be changed",run:change})}
  async remove(actor:string,workspaceId:string,userId:string,expectedUpdatedAt:string,idempotencyKey?:string){await this.authorization.requireWorkspace(actor,workspaceId,"admin");const expected=expectedTimestamp(expectedUpdatedAt);const remove=async()=>{const result=await this.store.revokeWorkspaceMembership(workspaceId,userId,expected);if(result==="not_found")throw new NotFoundError("Workspace membership not found");if(result==="owner")throw new ProductError("Workspace or project owner membership cannot be removed",409);if(result==="conflict")throw membershipChangedElsewhere();const timestamp=nowIso();for(const projectId of result.revokedProjectIds)await this.store.appendProjectAuditEvent({id:newId("audit"),projectId,actorId:actor,action:"membership.remove",status:"accepted",resourceKind:"member",resourceId:userId,createdAt:timestamp});return{deleted:true as const}};if(!idempotencyKey){await remove();return}await runIdempotentMutation({store:this.store,actorId:actor,scopeId:workspaceId,operation:"workspace.member.remove",key:idempotencyKey,request:{workspaceId,userId,expectedUpdatedAt:expected},resourceId:userId,failureMessage:"Workspace member could not be removed",run:remove})}
  async transferOwner(actor:string,workspaceId:string,targetUserId:string){const workspace=await this.authorization.requireWorkspace(actor,workspaceId,"admin");if(workspace.ownerUserId!==actor)throw new ProductError("Workspace owner access required",403);if(!(await this.store.transferWorkspaceOwner(workspaceId,actor,targetUserId.trim(),nowIso())))throw new ProductError("Target must be a different existing workspace member",409)}
  private async view(workspaceId:string,userId:string):Promise<WorkspaceMembershipView>{const member=(await this.store.listWorkspaceMemberships(workspaceId)).find((candidate)=>candidate.userId===userId);if(!member)throw new NotFoundError("Workspace membership not found");return member}
  private async find(identity:Identity):Promise<StoredUser>{const email=identity.email?.trim().toLowerCase();const issuer=identity.issuer?.trim();const subject=identity.subject?.trim();if((email&&(issuer||subject))||(!email&&!(issuer&&subject)))throw new ProductError("Specify either a verified email or an OIDC issuer and subject");const user=email?await this.store.findVerifiedUserByEmail(email):await this.store.findUserByOidcSubject(issuer!,subject!);if(!user?.emailVerified)throw new NotFoundError("Verified identity not found");return user}
}

function expectedTimestamp(value:string):string{if(!Number.isFinite(Date.parse(value)))throw new ProductError("expectedUpdatedAt must be an ISO timestamp");return new Date(value).toISOString()}
function nextTimestamp(previous:string):string{return new Date(Math.max(Date.now(),Date.parse(previous)+1)).toISOString()}
function membershipChangedElsewhere():ProductError{return new ProductError("Workspace membership changed elsewhere. Reload and try again.",409)}
